version: "3.7"

services:
    servidor_web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: servidor_web
        volumes:
            - type: bind
              source: ./Html
              target: /var/www/html        
        ports:
            - 80:80
        links:
            - servidor_bd
              
    servidor_bd:
        container_name: servidor_bd
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=Tarea
            - MYSQL_USER=devuser
            - MYSQL_PASSWORD=devpass
        ports:
            - 3306:3306
        volumes:
            - ./BD:/docker-entrypoint-initdb.d/
        restart: always
