version: "3.7"

services:
    servidor_web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: servidor_web
        volumes:
            - type: bind
              source: ./Html
              target: /var/www/html        
        ports:
            - 80:80
        depends_on:
            - servidor_bd
              
    servidor_bd:
        container_name: servidor_bd
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=sakila
            - MYSQL_USER=devuser
            - MYSQL_PASSWORD=devpass
        ports:
            - 3306:3306
        restart: always
        volumes:
            - type: bind
              source: ./sakila-db
              target: /home
